apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: elastic
spec:
  selector:
    app: apm-server
  ports:
  - name: http
    port: 8200
    targetPort: 8200
  - name: otlp-grpc
    port: 4317
    targetPort: 8200
  - name: otlp-http
    port: 4318
    targetPort: 8200
