apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  namespace: elastiflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: docker.elastic.co/demos/workshop/observability/elastiflix-node-server-otel-manual:8.9.0-10
        ports:
        - containerPort: 3001
        env:
        - name: API_ENDPOINT_FAVORITES
          value: python-favorite.elastiflix.svc.cluster.local:5000
        - name: API_ENDPOINT_LOGIN
          value: dotnet-login.elastiflix.svc.cluster.local:80
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.elastic.svc.cluster.local:9200
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: elastic123
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.otel-collector.svc.cluster.local:4317
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer local"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.version=1.0,deployment.environment=production,service.name=node-server
        - name: OTEL_LOG_LEVEL
          value: info
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/favorites
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: node-server
  namespace: elastiflix
spec:
  selector:
    app: node-server
  ports:
  - port: 3001
    targetPort: 3001
